### ISSUE TITLE
MDAnalysis develop incompatible with numpy 2.0

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/install-mdanalysis#9]
Related to https://github.com/MDAnalysis/cookiecutter-mdakit/issues/129 -- perhaps we should be pinning numpy here for now?

Retriggering last week's CI yields failures for micromamba as well, so this may go beyond pip: https://github.com/MDAnalysis/install-mdanalysis/actions/runs/9531795135/job/26546804394

**Comment by IAlibay** [comment]
Assuming CI passes on latest changes here: https://github.com/MDAnalysis/mdanalysis/pull/4620#pullrequestreview-2133812705

The best approach is to fix the wheel building for MDA imho. This will avoid potential dependency clashes and/or further issues if you happen to pick up numpy before or after this action.

> so this may go beyond pip

From a brief look, this is still `pip` related - the problem, as I see it, is that we're building MDA with a non 2.0 version but when picking up dependnecies (during the latter half of the pip install) it just picks up a newer version of numpy (because it can).

**Comment by IAlibay** [comment]
Ok I re-ran the last cron CI job and things seem to be good now: https://github.com/MDAnalysis/install-mdanalysis/actions/runs/9531795135

Are you happy with this solution @lilyminium ?

**Comment by lilyminium** [comment]
Yes that's perfect, thanks for the fix @IAlibay!
